site_name: Tastebuds
site_url: https://lindaqtran.github.io/Team11/
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Instructions: instructions.md
  - Marketing: product.md
theme: readthedocs
plugins:
  - mkdocs-video